modLoader="javafml" #mandatory
loaderVersion="20," #mandatory
license="MIT"

[[mods]] #mandatory
modId="not_enough_furniture" #mandatory
version="1.0" #mandatory
displayName="Not Enough Furniture" #mandatory
authors="Andro" #optional
displayURL = "https://github.com/Andr0medaDev/NotEnoughFurniture"
logoFile = "assets/not_enough_furniture/banner.png"
description='''Expansive Furniture Mod for Minecraft'''

[[dependencies.not_enough_furniture]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="${neo_version_range}" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.not_enough_furniture]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[modproperties.not_enough_furniture]
catalogueImageIcon = "assets/not_enough_furniture/icon.png"
catalogueBackground = "assets/not_enough_furniture/background.png"
